---
title: "Other Packages"
author: "David Chen"
date: "2022-12-09"
output: pdf_document
---

# Install packages
```{r setup, results='hide'}
pkgs <- c("riskRegression", "adjustedCurves", "CFsurvival", "survSuperLearner", "grf")
x <- lapply(pkgs, function(pkg) {
    if (!require(pkg, character.only = TRUE, quietly = TRUE)) {
        try(install.packages(pkg, quiet = ), silent = TRUE)
        try(remotes::install_github(paste0("tedwestling/", pkg)), silent = TRUE)
        require(pkg, character.only = TRUE)
    } else {
        cat(pkg, "loaded\n")
    }
})
```

# Simulated Data based on PBC using simPBC()

```{r pbc-sim}
library(survival)
library(data.table)
source("simPBC.R")
set.seed(0)
data <- as.data.table(simPBC(n = 1e3))
data <- data[, list(time, status, trt, age, sex, stage, logbili, protime)]
targtime <- 3:5 * 500
```

# RiskRegression

```{r}
data[, trt := factor(trt)]
treatment_model <- glm(trt ~ age + sex + stage, data = data, family = "binomial")
outcome_model <- CSC(Hist(time, status) ~ trt + age + sex + stage, data = data)
censor_model <-  coxph(Surv(time, status == 0) ~ trt + age + sex + stage, data = data, x = TRUE, y = TRUE)
rr1 <- ate(event = outcome_model, 
           treatment = treatment_model, 
           censor = censor_model, 
           data = data, 
           estimator = "AIPTW", 
           times = targtime, 
           cause = 1)
rr2 <- ate(event = outcome_model, 
           treatment = treatment_model, 
           censor = censor_model, 
           data = data, 
           estimator = "AIPTW", 
           times = targtime, 
           cause = 2)
data[, trt := as.numeric(trt) - 1]
```

# AdjustedCurves

```{r}
data[, trt := as.factor(trt)]

# DISCRETE-TIME TMLE USING SURVTMLE NOT RUN - LONG RUN TIME
## adjustedCurves AIPTW, at least for ate just uses riskRegression ----
cif1 <- adjustedcif(data = data,
                    variable = "trt",
                    ev_time = "time",
                    event = "status",
                    cause = 1,
                    method = "aiptw", 
                    conf_int = TRUE,
                    times = targtime, 
                    outcome_model = outcome_model, 
                    treatment_model = treatment_model
)

cif2 <- adjustedcif(data = data,
                    variable = "trt",
                    ev_time = "time",
                    event = "status",
                    cause = 2,
                    method = "aiptw",
                    conf_int = TRUE,
                    times = targtime, 
                    outcome_model = outcome_model, 
                    treatment_model = treatment_model
)

cif <- rbind(cbind("Event" = 1, cif1$adjcif), 
             cbind("Event" = 2, cif2$adjcif))

data[, trt := as.numeric(trt) - 1]
```

# CFSurvival

```{r}
# No obvious way to handle competing risks - long run time?
data[, status01 := as.numeric(status >= 1)][, trt := as.factor(trt)]

confounders <- model.matrix(~ -1 + ., data = data[, list(age, sex, stage)])
colnames(confounders) <- paste0("col", 1:ncol(confounders))
fit.time <- sort(union(targtime, unique(data[["time"]])))
fit.time <- fit.time[fit.time > 0 & fit.time <= max(data[["time"]][data[["status"]] > 0])]

t0 <- Sys.time()
cfs <- CFsurvival(time = data$time,
                  event = data$status01,
                  treat = as.numeric(data$trt) - 1,
                  confounders = confounders,
                  fit.times = fit.time)
t1 <- Sys.time()
eval.time <- t1 - t0

data[, trt := as.numeric(trt) - 1]
```

# GRF (Causal Forests)

```{r}
# No obvious way to handle competing risks
csf <- causal_survival_forest(X = confounders, Y = data$time, 
                              W = as.numeric(data$trt) - 1, D = data$status01, 
                              target = "survival.probability", horizon = 2500)
average_treatment_effect(csf)
```

# concrete

```{r}
library(concrete)
ConcreteArgs <- formatArguments(DataTable = data, 
                                EventTime = "time", 
                                EventType = "status", 
                                Treatment = "trt", 
                                Intervention = 0:1, 
                                TargetTime = 2000, 
                                TargetEvent = 1:2, 
                                Verbose = FALSE)
```

```{r}
ConcreteEst <- doConcrete(ConcreteArgs)
```

```{r}
ConcreteOut <- getOutput(ConcreteEst, A1 = 1, A0 = 2)
```

