# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeIC <- function(Hazards, TotalSurv, NuisanceWeight, GStar, T_tilde, Delta, EvalTimes, TargetEvent, TargetTime) {
    .Call('_concrete_computeIC', PACKAGE = 'concrete', Hazards, TotalSurv, NuisanceWeight, GStar, T_tilde, Delta, EvalTimes, TargetEvent, TargetTime)
}

updateHazardsCpp <- function(Hazards, TotalSurv, GStar, NuisanceWeight, EvalTimes, TargetEvent, TargetTime, PnEIC, OneStepEps, NormPnEIC) {
    .Call('_concrete_updateHazardsCpp', PACKAGE = 'concrete', Hazards, TotalSurv, GStar, NuisanceWeight, EvalTimes, TargetEvent, TargetTime, PnEIC, OneStepEps, NormPnEIC)
}

getCleverCovariate <- function(GStar, NuisanceWeight, hFS, LeqJ) {
    .Call('_concrete_getCleverCovariate', PACKAGE = 'concrete', GStar, NuisanceWeight, hFS, LeqJ)
}

getHazLS <- function(T_Tilde, EvalTimes, HazL) {
    .Call('_concrete_getHazLS', PACKAGE = 'concrete', T_Tilde, EvalTimes, HazL)
}

