# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit concrete.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(survival); library(data.table)


## ----PBC example, echo=TRUE, cache=TRUE, eval=FALSE---------------------------
#> # Prepare Data
#> library(concrete)
#> data <- survival::pbc[, c("time", "status", "trt", "age", "sex", "albumin")]
#> data <- subset(data, subset = !is.na(data$trt))
#> data$trt <- data$trt - 1
#> 
#> # Specify Analysis
#> ConcreteArgs <- formatArguments(
#>     DataTable = data,
#>     EventTime = "time", # name of event time variable
#>     EventType = "status", # name of event status variable
#>     Treatment = "trt", # name of treatment variable
#>     Intervention = 0:1, # 2 different static interventions
#>     TargetTime = 365.25/2 * (6:16), # 11 target times: 3-8 years biannually
#>     TargetEvent = 1:2, # 2 different competing risks
#>     CVArg = list(V = 10)
#> )
#> 
#> # Compute
#> ConcreteEst <- doConcrete(ConcreteArgs)
#> 
#> # Return Output
#> ConcreteOut <- getOutput(ConcreteEst, Estimand = "RD", Simultaneous = FALSE)
#> plot(ConcreteOut, ask = FALSE)


## ----formatargs, echo=TRUE, eval=FALSE----------------------------------------
#> ConcreteArgs <- formatArguments(
#>     DataTable = data,
#>     EventTime = "time", # name of event time variable
#>     EventType = "status", # name of event status variable
#>     Treatment = "trt", # name of treatment variable
#>     Intervention = 0:1, # 2 different static interventions
#>     TargetTime = 365.25/2 * (6:16), # 11 target times: 3-8 years biannually
#>     TargetEvent = 1:2, # 2 different competing risks
#>     CVArg = list(V = 10)
#> )


## ----concreteargs-model, echo=TRUE, eval=FALSE--------------------------------
#> ConcreteArgs$Model <- list(
#>     "trt" = c("SL.glmnet", "SL.bayesglm", "SL.xgboost", "SL.polymars"),
#>     "0" = NULL, # will use the default library
#>     "1" = list(Surv(time, status == 1) ~ trt, Surv(time, status == 1) ~ .),
#>     "2" = list("Surv(time, status == 2) ~ trt", "Surv(time, status == 2) ~ .")
#> )


## ----concreteargs-misc, echo=TRUE, eval=FALSE---------------------------------
#> # decrease the maximum tmle update number to 50
#> ConcreteArgs$MaxUpdateIter <- 50
#> 
#> # add a candidate regression with treatment interactions
#> ConcreteArgs[["Model"]][["2"]][[3]] <- "Surv(time, status == 2) ~ trt*."
#> 
#> # validate new estimation specification
#> ConcreteArgs <- formatArguments(ConcreteArgs)


## ----concreteargs-print, echo=TRUE, eval=FALSE--------------------------------
#> print(ConcreteArgs, Verbose = TRUE)


## ----concrete est, echo=TRUE, eval=FALSE--------------------------------------
#> ConcreteEst <- doConcrete(ConcreteArgs)


## ----concrete-est-print, echo=TRUE, eval=FALSE--------------------------------
#> print(ConcreteEst, Verbose  = TRUE)


## ----concrete-est-plot, echo=TRUE, eval=FALSE---------------------------------
#> plot(ConcreteEst, ask  = FALSE)


## ----concrete-out, echo=TRUE, eval=FALSE--------------------------------------
#> ConcreteOut <- getOutput(ConcreteEst = ConcreteEst, Estimand = "RD",
#> 			 Intervention = 1:2, GComp = TRUE, Simultaneous = TRUE, Signif = 0.05)
#> head(ConcreteOut, 12)


## ----concrete-out-plot, echo=TRUE, eval=FALSE---------------------------------
#> plot(ConcreteOut, NullLine = TRUE, ask = FALSE)

